env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  parser: 'babel-eslint'
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
    dynamicImport: true
plugins:
  - vue
rules: {}
